# [jobs.lexer]
# image = { source = "dockerfile", path = "."}

# run = [
#   "./Lex $input",
# ]

# 一个示例
[jobs.lab1]

image = { source = "dockerfile", path = "." }

run = [
    "ls",
    "./init.sh $input $ir",
]