# [jobs.lexer]
# image = { source = "dockerfile", path = "."}

# run = [
#   "./Lex $input",
# ]

# 一个示例
[jobs.mdarray]

image = { source = "dockerfile", path = "." }

run = [
    "java -Dfile.encoding=UTF-8 -cp './bin:./lib/antlr-4.9-complete.jar' App $input $ir",
]
